/*
 * Uber API
 *
 * Move your app forward with the Uber API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelError struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Fields string `json:"fields,omitempty"`
}
