/*
 * Uber API
 *
 * Move your app forward with the Uber API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Activity struct {

	// Unique identifier for the activity
	Uuid string `json:"uuid,omitempty"`
}
